### ISSUE TITLE
Adding required image dimensions makes the attribute itself required

### ISSUE THREAD

**Issue by thomassvensen** [markeverard/Chief2moro.ImageDataExtensions#3]
Is it by design that adding `RequiredImageSize` attribute also make the image property itself required? I would prefer that this:

```
  if (contentReference == null)
        {
                ErrorMessage = "RequiredImageSize attribute should only be applied to ContentReference properties";
                return false;
        }
```

was replaced by

```
  if (contentReference == null)
        {
            return true;
        }
```

Would you accept a pull request? :-)

**Comment by markeverard** [comment]
Better late than never right! I'd always accept a pull request. As part of the upgrade pull request that @LucGosso submitted I've dropped in your suggested change. You are right in that the behaviour you described wasn't by design ;)

There will be a new package in the Episerver feed in the next couple of days
