### ISSUE TITLE
EPiServer 10 support

### ISSUE THREAD

**Issue by jonatanjii** [markeverard/Chief2moro.ImageDataExtensions#5]
Hi,
Regarding the move of the ThumbnailManager to the EPiServer.Core.Internal namespace in EPiServer 10, do you plan a new release?

/Jonatan

**Comment by markeverard** [comment]
I wasn't planning one, exactly because of the ThumbnailManager becoming an unsupported API. However @LucGosso did the hard work so there will now be a new package submitted. It will still be a USE AT OWN RISK purely because of the dependency on the internal namespace. There is now an abstraction where you can provide your own resizing functionality. There is another package demonstrating this using ImageResizer

**Comment by LucGosso** [comment]
Chief2moro.ImageDataExtensions.ImageResizer looks nice @markeverard , will you write more about it? 
Also the link on epinuget to the project site on github is wrong...

**Comment by markeverard** [comment]
Blog post published [http://www.markeverard.com/2017/03/16/imagedataextensions-for-episerver-10/](http://www.markeverard.com/2017/03/16/imagedataextensions-for-episerver-10/)

Thanks for the heads up about the broken project link. Its a bad nuspec file. The project is actually contained in the same repo - [https://github.com/markeverard/Chief2moro.ImageDataExtensions/tree/master/src/Chief2moro.ImageDataExtensions.ImageResizer](https://github.com/markeverard/Chief2moro.ImageDataExtensions/tree/master/src/Chief2moro.ImageDataExtensions.ImageResizer)
